name: Keep-alive Heartbeat

on:
  schedule:
    - cron: '0 0 1 * *' 
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Manual Custom Heartbeat
        env:
        # Map your secret to an environment variable for the script
          MY_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name "GitHub Action Heartbeat 1"
          git config --global user.email "actions@github.com"
        
          echo "Last heartbeat: $(date)" > heartbeat.txt
        
          git add heartbeat.txt
          git commit -m "chore: automated heartbeat to keep actions alive [skip ci]" || echo "No changes to commit"
        
          # Use the token in the remote URL for the push
          git push https://x-access-token:${MY_TOKEN}@github.com/${{ github.repository }}.git HEAD:main